src/Entity/Marque.php
<?php

namespace App\Entity;

use App\Repository\MarqueRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MarqueRepository::class)]
class Marque
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom_marque = null;

    /**
     * @var Collection<int, Product>
     */
    #[ORM\OneToMany(targetEntity: Product::class, mappedBy: 'id_marque')]
    private Collection $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomMarque(): ?string
    {
        return $this->nom_marque;
    }

    public function setNomMarque(string $nom_marque): static
    {
        $this->nom_marque = $nom_marque;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): static
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
            $product->setIdMarque($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): static
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getIdMarque() === $this) {
                $product->setIdMarque(null);
            }
        }

        return $this;
    }
}

src/Form/MarqueType.php
<?php

namespace App\Form;

use App\Entity\Marque;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MarqueType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_marque')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Marque::class,
        ]);
    }
}

src/Controller/MarqueController.php
<?php

namespace App\Controller;

use App\Entity\Marque;
use App\Form\MarqueType;
use App\Repository\MarqueRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/marque')]
final class MarqueController extends AbstractController
{
    #[Route(name: 'app_marque_index', methods: ['GET'])]
    public function index(MarqueRepository $marqueRepository): Response
    {
        return $this->render('marque/index.html.twig', [
            'marques' => $marqueRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_marque_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $marque = new Marque();
        $form = $this->createForm(MarqueType::class, $marque);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($marque);
            $entityManager->flush();

            return $this->redirectToRoute('app_marque_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('marque/new.html.twig', [
            'marque' => $marque,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_marque_show', methods: ['GET'])]
    public function show(Marque $marque): Response
    {
        return $this->render('marque/show.html.twig', [
            'marque' => $marque,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_marque_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Marque $marque, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MarqueType::class, $marque);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_marque_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('marque/edit.html.twig', [
            'marque' => $marque,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_marque_delete', methods: ['POST'])]
    public function delete(Request $request, Marque $marque, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$marque->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($marque);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_marque_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/marque/_delete_form.html.twig
<form method="post" action="{{ path('app_marque_delete', {'id': marque.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ marque.id) }}">
    <button class="btn">Delete</button>
</form>

templates/marque/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/marque/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Marque{% endblock %}

{% block body %}
    <h1>Edit Marque</h1>

    {{ include('marque/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_marque_index') }}">back to list</a>

    {{ include('marque/_delete_form.html.twig') }}
{% endblock %}

templates/marque/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Marque index{% endblock %}
{% block etiquette %}Nos marques{% endblock %}
{% block section %}Liste des marques{% endblock %}
{% block body %}
    <h1>Marque index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_marque</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for marque in marques %}
            <tr>
                <td>{{ marque.id }}</td>
                <td>{{ marque.nomMarque }}</td>
                <td>
                    <a href="{{ path('app_marque_show', {'id': marque.id}) }}" class="btn btn-primary">show</a>
                    <a href="{{ path('app_marque_edit', {'id': marque.id}) }}" class="btn btn-warning">edit</a>


                </td>
                
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        <a href="{{ path('app_marque_new') }}" class="btn btn-success">Create new</a>
        </tbody>
    </table>

    
{% endblock %}

templates/marque/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Marque{% endblock %}

{% block body %}
    <h1>Create new Marque</h1>

    {{ include('marque/_form.html.twig') }}

    <a href="{{ path('app_marque_index') }}">back to list</a>
{% endblock %}

templates/marque/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Marque{% endblock %}

{% block body %}
    <h1>Marque</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ marque.id }}</td>
            </tr>
            <tr>
                <th>Nom_marque</th>
                <td>{{ marque.nomMarque }}</td>
            </tr>
              <tr>
                <th>action</th>
                <td>                    
                <a href="{{ path('app_marque_index') }}">back to list</a>
                <a href="{{ path('app_marque_edit', {'id': product.id}) }}">edit</a></td>
        </tbody>
        </tbody>
    </table>

    {{ include('marque/_delete_form.html.twig') }}
{% endblock %}